version: "3.9"
services:
  db:
    image: postgres:15
    container_name: nestory_db
    restart: always
    environment:
      POSTGRES_USER: nestory_user
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: nestory
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
