"""update persons table

Revision ID: 0c35510609fe
Revises: b9c9c39f1a94
Create Date: 2025-05-05 20:46:46.109357

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c35510609fe"
down_revision: Union[str, None] = "b9c9c39f1a94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("persons", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("persons", sa.Column("last_name", sa.String(), nullable=True))
    op.drop_index("ix_persons_full_name", table_name="persons")
    op.create_index(
        op.f("ix_persons_first_name"), "persons", ["first_name"], unique=False
    )
    op.create_index(
        op.f("ix_persons_last_name"), "persons", ["last_name"], unique=False
    )
    op.drop_column("persons", "full_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "persons",
        sa.Column("full_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_persons_last_name"), table_name="persons")
    op.drop_index(op.f("ix_persons_first_name"), table_name="persons")
    op.create_index("ix_persons_full_name", "persons", ["full_name"], unique=False)
    op.drop_column("persons", "last_name")
    op.drop_column("persons", "first_name")
    # ### end Alembic commands ###
