"""create person and tree tables

Revision ID: 876bb1bc12ac
Revises:
Create Date: 2025-05-04 23:57:05.292129

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "876bb1bc12ac"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trees_id"), "trees", ["id"], unique=False)
    op.create_table(
        "persons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("photo_url", sa.String(), nullable=True),
        sa.Column("tree_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tree_id"],
            ["trees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_persons_full_name"), "persons", ["full_name"], unique=False
    )
    op.create_index(op.f("ix_persons_id"), "persons", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_persons_id"), table_name="persons")
    op.drop_index(op.f("ix_persons_full_name"), table_name="persons")
    op.drop_table("persons")
    op.drop_index(op.f("ix_trees_id"), table_name="trees")
    op.drop_table("trees")
    # ### end Alembic commands ###
