"""update persons table

Revision ID: b9c9c39f1a94
Revises: 32ff2fa37000
Create Date: 2025-05-05 20:45:23.295782

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "b9c9c39f1a94"
down_revision: Union[str, None] = "32ff2fa37000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
